Repository BearStudio/start-ui-web, pull requests merged in 2022-07, with the labels that each got.

#245 feat: Improve fields feedback UX
  src/components/FieldBooleanCheckbox/docs.stories.tsx
  src/components/FieldBooleanCheckbox/index.tsx
  src/components/FieldCheckboxes/docs.stories.tsx
  src/components/FieldCheckboxes/index.tsx
  src/components/FieldCurrency/docs.stories.tsx
  src/components/FieldCurrency/index.tsx
  src/components/FieldDayPicker/docs.stories.tsx
  src/components/FieldDayPicker/index.tsx
  src/components/FieldHidden/docs.stories.tsx
  src/components/FieldHidden/index.tsx
  src/components/FieldInput/docs.stories.tsx
  src/components/FieldInput/index.tsx
  src/components/FieldMultiSelect/docs.stories.tsx
  src/components/FieldMultiSelect/index.tsx
  src/components/FieldRadios/docs.stories.tsx
  src/components/FieldRadios/index.tsx
  src/components/FieldSelect/docs.stories.tsx
  src/components/FieldSelect/index.tsx
  src/components/FieldTextarea/docs.stories.tsx
  src/components/FieldTextarea/index.tsx
Labels: changelog

#246 fix: Init dayjs with the current language on first load
  src/config/dayjs.ts
  src/config/i18next.ts
Labels: bug, changelog

#247 fix: DateAgo array dependencies with stable reference
  src/components/DateAgo/index.tsx
Labels: changelog

#248 feat: Add custom theme tokens typing
  package.json
  src/theme/externals-css.ts
  src/theme/externals/reactDayPicker.ts
  src/theme/foundations/typography.ts
  src/theme/index.ts
  src/theme/theme.ts
  yarn.lock
Labels: enhancement, changelog

#235 Change hard coded strings to const for routing and API error keys
  src/app/account/account.service.ts
  src/app/admin/users/users.service.ts
Labels: changelog

#252 fix: Error with loadingMessage in Select component
  src/components/Select/docs.stories.tsx
  src/components/Select/index.tsx
Labels: bug, changelog

#256 feat: Add environment variables validations
  .env.example
  .env.validator.js
  next.config.js
  package.json
  yarn.lock
Labels: changelog

#259 feat: Add better Error pages
  src/app/App.tsx
  src/app/account/AccountRoutes.tsx
  src/app/admin/AdminRoutes.tsx
  src/app/admin/users/AdminUsersRoutes.tsx
  src/app/admin/users/PageUserUpdate.tsx
  src/app/dashboard/DashboardRoutes.tsx
  src/app/router/guards/AdminRouteGuard.tsx
  src/app/router/guards/AuthenticatedRouteGuard.tsx
  src/app/router/guards/PublicOnlyRouteGuard.tsx
  src/components/ErrorBoundary/docs.stories.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/ErrorPage/Illustration403.tsx
  src/components/ErrorPage/Illustration404.tsx
  src/components/ErrorPage/IllustrationDefault.tsx
  src/components/ErrorPage/docs.stories.tsx
  src/components/ErrorPage/index.tsx
  src/errors/Error403.tsx
  src/errors/Error404.tsx
  src/errors/ErrorBoundary.tsx
  src/errors/index.ts
  src/locales/ar/components.json
  src/locales/ar/errors.json
  src/locales/ar/index.ts
  src/locales/en/components.json
  src/locales/en/errors.json
  src/locales/en/index.ts
  src/locales/fr/components.json
  src/locales/fr/errors.json
  src/locales/fr/index.ts
  src/pages/500.tsx
  src/pages/_app.tsx
Labels: changelog

#260 feat: upgrade to tanstack react query 4
  package.json
  src/Providers.tsx
  src/app/App.tsx
  src/app/account/PageProfile.tsx
  src/app/account/account.service.ts
  src/app/admin/users/users.service.ts
  src/app/auth/LoginModalInterceptor.tsx
  src/app/auth/PageLogin.tsx
  src/app/auth/PageLogout.tsx
  src/app/auth/auth.service.ts
  yarn.lock
Labels: changelog

#266 fix: Husky hooks with Prettier
  package.json
Labels: bug, changelog

#267 fix: Docker image build
  Dockerfile
Labels: bug
